### ISSUE TITLE
Using downstream.py with BCI Competition IV 2a dataset

### ISSUE THREAD

**Issue by SalehAce1** [SPOClab-ca/BENDR#8]
Hello,

I'm trying to use the BCI Competition IV 2a data from here http://bbci.de/competition/iv/
The files I get have the .gdf extension. Here is how I setup my downstream.yml:

```
Configuratron:
  use_only:
    - bci_iv_2a
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False

encoder_weights: "configs/models/encoder.pt" 
context_weights: "configs/models/contextualizer.pt"

datasets: !include configs/downstream_datasets.yml
```

and here is my downstream_datasets.yml:

```
bci_iv_2a:
  name: "BCI Competition IV 2a"
  toplevel: configs/datasets/bci
  tmin: -2
  tlen: 6
  data_max: 100
  data_min: -100
  extensions:
          - .gdf
  picks:
    - eeg
  train_params:
    epochs: 15
    batch_size: 60 # This dataset likes batches of ~60 (community is overfitting this)
  lr: 0.00005
```

Once I run downstream.py using the command: 
`python3 downstream.py BENDR --random-init --results-filename "results/BENDR_random_init.xlsx"`
I get the error: 

> Skipping A08T.gdf. Exception: ('No stim channels found, but the raw object has annotations. Consider using mne.events_from_annotations to convert these to events.',).

I am not sure how to proceed from here.

Thank you.
